---
title: "Homework 6"
author: Laura Bulmer
date: 12/2/2024
output: github_document
---

Before starting on the problems, I'm setting up my libraries and options for visuals. 

```{r setting up}
library(p8105.datasets)
library(tidyverse)
library(ggridges)
library(patchwork)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1 

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Problem 2

```{r}
# Loading in the data. 

homicides_raw= 
  read_csv("data/homicide-data.csv")

# Creating a city_state variable and solved binary variable, and filtering.

homicides_df <- 
  homicides_raw %>%
  mutate(
    city_state = paste(city, state, sep = ", "),
    solved = case_when(
      disposition %in% c("Open/No arrest", "Closed without arrest") ~ 0,
      disposition == "Closed by arrest" ~ 1,
      TRUE ~ NA_real_
    ),
    victim_age = as.numeric(victim_age)
  )%>%
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", 
                       "Tulsa, AL"),
    victim_race %in% c("White", "Black")
    )
```

```{r}
# Fitting the logistic regression model for Baltimore, MD.

baltimore = glm(
  solved ~ victim_age + victim_sex + victim_race,
  data = homicides_df %>% filter(city_state == "Baltimore, MD"),
  family = binomial()
) %>%
  broom::tidy(conf.int=TRUE) 

baltimore

# Estimate and CI of adjusted OR for solving homicides comparing genders

victim_sex_odds_ratio = baltimore %>%
  filter(term == "victim_sexMale") %>%
  mutate(
    odds_ratio = exp(estimate),
    conf_low = exp(conf.low),
    conf_high = exp(conf.high)
  ) %>%
  select(term, odds_ratio, conf_low, conf_high)

victim_sex_odds_ratio
```

```{r}

# Creating tidy pipeline to do the same for all cities.

all_city_results = homicides_df %>%
  group_by(city_state) %>%
  nest() %>%
  mutate(
    model = map(data, ~glm(
      solved ~ victim_age + victim_sex + victim_race,
      data = .x, 
      family = binomial)
    ),
    results = map(model, ~ broom::tidy(.x, conf.int=TRUE))
    ) %>%
  unnest(cols = c(results)) %>%
  filter(term == "victim_sexMale") %>%
  mutate(
    odds_ratio = exp(estimate),
    conf_low = exp(conf.low),
    conf_high = exp(conf.high)
  ) %>%
  select(term, odds_ratio, conf_low, conf_high)

all_city_results
```

```{r fig.width=8, fig.height=10}
# Plotting the ORs and CIs

all_city_results%>%
  mutate(city_state = factor(city_state, levels = city_state)) %>%
  ggplot(aes(x = reorder(city_state, odds_ratio), y = odds_ratio)) +
  geom_point(color = "blue", size = 3) +
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high), width = 0.2) +
  coord_flip() + 
  labs(
    title = "OR of Unsolved Homicides Comparing Male Victims to Females",
    x = "City",
    y = "OR of Unsolved Homicides for Males Compared to Females"
  )
```

ADD COMMENT HERE

## Problem 3

